use_frameworks!

platform :ios, '11.0'

target 'SeamlessPayDemo' do
  pod 'SeamlessPayCore', :path => '../'
end

target 'SeamlessPay_ObjC' do
  pod 'SeamlessPayCore', :path => '../'
end

target 'SeamlessPay_Swift' do
  pod 'SeamlessPayCore', :path => '../'
end

target 'SeamlessPayCoreTests' do
  pod 'SeamlessPayCore', :path => '../'
end
