disabled_rules: # rule identifiers to exclude from running
  - large_tuple
  - todo
  - trailing_comma
  - unused_optional_binding
opt_in_rules:
  - overridden_super_call

line_length: 120
function_body_length: 80
nesting:
  type_level: 3

identifier_name:
  allowed_symbols: "_"
  excluded:
    - id
    - x
    - y
cyclomatic_complexity: 20
