version: 2.1

jobs:
  build:
    macos:
      xcode: 26.0.1
    working_directory: ~/seamlesspay-ios
    steps:
      - checkout
      - run:
          name: Run tests for the Package
          no_output_timeout: 5m
          command: |
            xcodebuild \
              -workspace ./.swiftpm/xcode/package.xcworkspace \
              -scheme SeamlessPay \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 17' \
              -enableCodeCoverage YES \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              test
